version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    tty: true
    environment:
      DEBUG: "true"
      LINE_CHANNEL_SECRET: "LINE_CHANNEL_SECRET"
      LINE_CHANNEL_TOKEN: "LINE_CHANNEL_TOKEN"
    ports:
      - "8000:8000"
    volumes:
      - ../:/workspace
